/**
 * GitHub remote detection and policy state file I/O (M5).
 *
 * Detects the GitHub "owner/repo" from a git worktree, builds per-session
 * GitHubPolicy objects, and manages the policy state JSON file that the
 * gh shim reads at invocation time.
 */

import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { chmod, mkdir, readdir, readFile, writeFile, rm } from "node:fs/promises";
import { join } from "node:path";
import { POLICY_DIR } from "./sandbox.js";
import type { GitHubPolicy } from "./types.js";

const execFileAsync = promisify(execFile);

/**
 * Detect the GitHub "owner/repo" from the git remote in a directory.
 * Parses the origin remote URL (HTTPS or SSH format).
 * Returns null if no GitHub remote is found.
 */
export async function detectGitHubRepo(cwd: string): Promise<string | null> {
  try {
    const { stdout } = await execFileAsync("git", ["-C", cwd, "remote", "get-url", "origin"]);
    return parseGitHubRemoteUrl(stdout.trim());
  } catch {
    return null;
  }
}

/**
 * Parse a git remote URL and extract "owner/repo" if it's a GitHub remote.
 * Handles:
 *   - https://github.com/owner/repo.git
 *   - https://github.com/owner/repo
 *   - git@github.com:owner/repo.git
 *   - git@github.com:owner/repo
 *   - ssh://git@github.com/owner/repo.git
 */
export function parseGitHubRemoteUrl(url: string): string | null {
  // HTTPS: https://github.com/owner/repo[.git]
  const httpsMatch = url.match(/^https?:\/\/github\.com\/([^/]+\/[^/]+?)(?:\.git)?$/);
  if (httpsMatch) return httpsMatch[1];

  // SSH shorthand: git@github.com:owner/repo[.git]
  const sshMatch = url.match(/^git@github\.com:([^/]+\/[^/]+?)(?:\.git)?$/);
  if (sshMatch) return sshMatch[1];

  // SSH URL: ssh://git@github.com/owner/repo[.git]
  const sshUrlMatch = url.match(/^ssh:\/\/git@github\.com\/([^/]+\/[^/]+?)(?:\.git)?$/);
  if (sshUrlMatch) return sshUrlMatch[1];

  return null;
}

/**
 * Build a GitHubPolicy for a new session.
 */
export function buildSessionPolicy(repo: string, branch: string): GitHubPolicy {
  return {
    repo,
    allowedPushRefs: [branch],
    ownedPrNumber: null,
    canCreatePr: true,
  };
}

/**
 * Path to the policy state file for a session.
 */
export function policyStatePath(sessionId: string): string {
  return join(POLICY_DIR, `${sessionId}-github-policy.json`);
}

/**
 * Write the policy state file. Called at session creation and
 * updated by the gh shim after PR creation.
 */
export async function writePolicyState(sessionId: string, policy: GitHubPolicy): Promise<void> {
  await mkdir(POLICY_DIR, { recursive: true });
  await writeFile(policyStatePath(sessionId), JSON.stringify(policy, null, 2), "utf-8");
}

/**
 * Read the policy state file. Called by the gh shim on each invocation.
 */
export async function readPolicyState(path: string): Promise<GitHubPolicy> {
  const content = await readFile(path, "utf-8");
  return JSON.parse(content) as GitHubPolicy;
}

/**
 * Clean up the policy state file for a session.
 */
export async function cleanupPolicyState(sessionId: string): Promise<void> {
  try {
    await rm(policyStatePath(sessionId));
  } catch {
    // File may not exist — that's fine
  }
}

// --- gh shim installation ---

/**
 * Path to the shim bin directory for a session.
 */
export function shimBinDir(sessionId: string): string {
  return join(POLICY_DIR, `bin-${sessionId}`);
}

/**
 * Install the gh shim wrapper for a session.
 * Creates a bin directory with a `gh` script that delegates to gh-shim.ts.
 * Returns the bin directory path (for PATH prepending).
 */
export async function installGhShim(
  sessionId: string,
  ghShimTsPath: string,
  nodePath: string,
): Promise<string> {
  const dir = shimBinDir(sessionId);
  await mkdir(dir, { recursive: true });

  const shimScript = `#!/bin/bash
# Bouncer gh shim — delegates to gh-shim.ts with policy enforcement.
# Generated by Bouncer session manager — do not edit.
exec "${nodePath}" --import tsx/esm "${ghShimTsPath}" "$@"
`;

  const shimPath = join(dir, "gh");
  await writeFile(shimPath, shimScript, "utf-8");
  await chmod(shimPath, 0o755);
  return dir;
}

/**
 * Clean up the gh shim bin directory for a session.
 */
export async function cleanupGhShim(sessionId: string): Promise<void> {
  await rm(shimBinDir(sessionId), { recursive: true, force: true });
}

/**
 * Find the real gh binary. Caches the result.
 * Returns null if gh is not installed.
 */
let cachedRealGh: string | null | undefined = undefined;
export async function findRealGh(): Promise<string | null> {
  if (cachedRealGh !== undefined) return cachedRealGh;
  try {
    const { stdout } = await execFileAsync("which", ["gh"]);
    const path = stdout.trim();
    cachedRealGh = path || null;
  } catch {
    cachedRealGh = null;
  }
  return cachedRealGh;
}

// --- Orphan cleanup ---

/**
 * Clean up orphan GitHub policy artifacts (policy state files, hooks dirs,
 * shim bin dirs, allowed-refs files) left behind by crashed sessions.
 */
export async function cleanupOrphanGitHubArtifacts(activeIds: Set<string>): Promise<void> {
  let entries: string[];
  try {
    entries = await readdir(POLICY_DIR);
  } catch {
    return; // Directory may not exist
  }

  for (const entry of entries) {
    // Match patterns: {sessionId}-github-policy.json, {sessionId}-hooks, bin-{sessionId}, {sessionId}-allowed-refs.txt
    let sessionId: string | null = null;

    const policyMatch = entry.match(/^(.+)-github-policy\.json$/);
    if (policyMatch) sessionId = policyMatch[1];

    const hooksMatch = entry.match(/^(.+)-hooks$/);
    if (hooksMatch) sessionId = hooksMatch[1];

    const binMatch = entry.match(/^bin-(.+)$/);
    if (binMatch) sessionId = binMatch[1];

    const refsMatch = entry.match(/^(.+)-allowed-refs\.txt$/);
    if (refsMatch) sessionId = refsMatch[1];

    if (sessionId && !activeIds.has(sessionId)) {
      try {
        await rm(join(POLICY_DIR, entry), { recursive: true, force: true });
      } catch {
        // Best effort
      }
    }
  }
}
