/**
 * Git hook installation and cleanup for session policy enforcement (M5).
 *
 * Installs a pre-push hook that restricts pushes to allowed refs.
 * The hook reads an allowed-refs.txt file (one ref per line) written
 * alongside the policy state JSON — no JSON parsing in bash needed.
 */

import { mkdir, writeFile, chmod, rm } from 'node:fs/promises';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { join } from 'node:path';
import { POLICY_DIR } from './sandbox.js';

const execFileAsync = promisify(execFile);

/**
 * Path to the hooks directory for a session.
 */
export function hooksDir(sessionId: string): string {
  return join(POLICY_DIR, `${sessionId}-hooks`);
}

/**
 * Path to the allowed-refs file for a session.
 */
export function allowedRefsPath(sessionId: string): string {
  return join(POLICY_DIR, `${sessionId}-allowed-refs.txt`);
}

/**
 * Path to the protected-branches file for a session.
 */
export function protectedBranchesPath(sessionId: string): string {
  return join(POLICY_DIR, `${sessionId}-protected-branches.txt`);
}

/**
 * Generate the pre-push hook script content.
 * Reads allowed refs from a plain text file (one per line).
 * Supports wildcard patterns (e.g., "refs/heads/*") and a separate
 * protected-branches file for branches that are always denied.
 */
export function generatePrePushHook(allowedRefsFile: string): string {
  // Derive protected-branches file path from allowed-refs file path
  const protectedFile = allowedRefsFile.replace('allowed-refs.txt', 'protected-branches.txt');
  return `#!/bin/bash
# Bouncer pre-push hook: restrict pushes to allowed refs.
# Generated by Bouncer session manager — do not edit.

ALLOWED_REFS_FILE="${allowedRefsFile}"
PROTECTED_FILE="${protectedFile}"

if [ ! -f "$ALLOWED_REFS_FILE" ]; then
  echo "[bouncer:git] allowed-refs file not found, denying push" >&2
  exit 1
fi

# pre-push receives lines on stdin: <local-ref> <local-sha> <remote-ref> <remote-sha>
while read -r local_ref local_sha remote_ref remote_sha; do
  # Extract the branch name from the remote ref
  remote_branch="\${remote_ref#refs/heads/}"

  # Check protected branches first
  if [ -f "$PROTECTED_FILE" ]; then
    while IFS= read -r protected; do
      if [ "$remote_branch" = "$protected" ]; then
        echo "[bouncer:git] DENY push to $remote_branch — protected branch" >&2
        exit 1
      fi
    done < "$PROTECTED_FILE"
  fi

  allowed=false
  while IFS= read -r ref; do
    # Exact match (full ref or bare branch)
    if [ "$remote_branch" = "$ref" ] || [ "refs/heads/$remote_branch" = "$ref" ]; then
      allowed=true
      break
    fi
    # Wildcard match: refs/heads/* matches any branch
    case "$ref" in
      */\\*)
        prefix="\${ref%\\*}"
        if [ "refs/heads/$remote_branch" != "\${refs/heads/$remote_branch#$prefix}" ]; then
          allowed=true
          break
        fi
        ;;
    esac
    # Simple wildcard: refs/heads/*
    if [ "$ref" = "refs/heads/*" ]; then
      allowed=true
      break
    fi
  done < "$ALLOWED_REFS_FILE"

  if [ "$allowed" = false ]; then
    echo "[bouncer:git] DENY push to $remote_branch — ref not in allowed list" >&2
    exit 1
  fi
  echo "[bouncer:git] ALLOW push to $remote_branch" >&2
done

exit 0
`;
}

/**
 * Generate the pre-push hook for container use.
 * Same logic as generatePrePushHook, but with a hardcoded container path
 * for the allowed-refs file (mounted at /etc/bouncer/allowed-refs.txt).
 */
export function generatePrePushHookForContainer(): string {
  return generatePrePushHook('/etc/bouncer/allowed-refs.txt');
}

/**
 * Install the pre-push hook for a session.
 * Creates the hooks directory, writes the hook script, allowed-refs file,
 * and protected-branches file, and sets core.hooksPath in the worktree's git config.
 */
export async function installHooks(
  sessionId: string,
  worktreePath: string,
  allowedPushRefs: string[],
  protectedBranches: string[] = [],
): Promise<void> {
  const dir = hooksDir(sessionId);
  await mkdir(dir, { recursive: true });

  // Write the allowed-refs companion file
  const refsFile = allowedRefsPath(sessionId);
  await writeFile(refsFile, allowedPushRefs.join('\n') + '\n', 'utf-8');

  // Write the protected-branches companion file
  const protectedFile = protectedBranchesPath(sessionId);
  await writeFile(protectedFile, protectedBranches.join('\n') + '\n', 'utf-8');

  // Write the pre-push hook
  const hookPath = join(dir, 'pre-push');
  await writeFile(hookPath, generatePrePushHook(refsFile), 'utf-8');
  await chmod(hookPath, 0o755);

  // Point the worktree's git config to our hooks directory
  await execFileAsync('git', ['-C', worktreePath, 'config', 'core.hooksPath', dir]);
}

/**
 * Update the allowed-refs file for a session (e.g., after branch ratchet).
 */
export async function updateAllowedRefs(
  sessionId: string,
  allowedPushRefs: string[],
): Promise<void> {
  const refsFile = allowedRefsPath(sessionId);
  await writeFile(refsFile, allowedPushRefs.join('\n') + '\n', 'utf-8');
}

/**
 * Remove the hooks directory, allowed-refs file, and unset core.hooksPath.
 */
export async function cleanupHooks(sessionId: string, worktreePath: string): Promise<void> {
  // Unset core.hooksPath (catch errors — worktree may already be gone)
  try {
    await execFileAsync('git', ['-C', worktreePath, 'config', '--unset', 'core.hooksPath']);
  } catch {
    // Worktree may be gone or config already unset
  }

  // Remove hooks directory, allowed-refs file, and protected-branches file
  await rm(hooksDir(sessionId), { recursive: true, force: true });
  try {
    await rm(allowedRefsPath(sessionId));
  } catch {
    // May not exist
  }
  try {
    await rm(protectedBranchesPath(sessionId));
  } catch {
    // May not exist
  }
}
