/**
 * Git hook installation and cleanup for session policy enforcement (M5).
 *
 * Installs a pre-push hook that restricts pushes to allowed refs.
 * The hook reads an allowed-refs.txt file (one ref per line) written
 * alongside the policy state JSON — no JSON parsing in bash needed.
 */

import { mkdir, writeFile, chmod, rm } from "node:fs/promises";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { join } from "node:path";
import { POLICY_DIR } from "./sandbox.js";

const execFileAsync = promisify(execFile);

/**
 * Path to the hooks directory for a session.
 */
export function hooksDir(sessionId: string): string {
  return join(POLICY_DIR, `${sessionId}-hooks`);
}

/**
 * Path to the allowed-refs file for a session.
 */
export function allowedRefsPath(sessionId: string): string {
  return join(POLICY_DIR, `${sessionId}-allowed-refs.txt`);
}

/**
 * Generate the pre-push hook script content.
 * Reads allowed refs from a plain text file (one per line).
 */
export function generatePrePushHook(allowedRefsFile: string): string {
  return `#!/bin/bash
# Bouncer pre-push hook: restrict pushes to allowed refs.
# Generated by Bouncer session manager — do not edit.

ALLOWED_REFS_FILE="${allowedRefsFile}"

if [ ! -f "$ALLOWED_REFS_FILE" ]; then
  echo "[bouncer:git] policy file not found, denying push" >&2
  exit 1
fi

# pre-push receives lines on stdin: <local-ref> <local-sha> <remote-ref> <remote-sha>
while read local_ref local_sha remote_ref remote_sha; do
  # Extract the branch name from the remote ref
  remote_branch="\${remote_ref#refs/heads/}"

  allowed=false
  while IFS= read -r ref; do
    if [ "$remote_branch" = "$ref" ]; then
      allowed=true
      break
    fi
  done < "$ALLOWED_REFS_FILE"

  if [ "$allowed" = false ]; then
    echo "[bouncer:git] push to '$remote_branch' denied by session policy" >&2
    echo "[bouncer:git] allowed refs: $(cat "$ALLOWED_REFS_FILE" | tr '\\n' ', ')" >&2
    exit 1
  fi
done

exit 0
`;
}

/**
 * Install the pre-push hook for a session.
 * Creates the hooks directory, writes the hook script and allowed-refs file,
 * and sets core.hooksPath in the worktree's git config.
 */
export async function installHooks(
  sessionId: string,
  worktreePath: string,
  allowedPushRefs: string[],
): Promise<void> {
  const dir = hooksDir(sessionId);
  await mkdir(dir, { recursive: true });

  // Write the allowed-refs companion file
  const refsFile = allowedRefsPath(sessionId);
  await writeFile(refsFile, allowedPushRefs.join("\n") + "\n", "utf-8");

  // Write the pre-push hook
  const hookPath = join(dir, "pre-push");
  await writeFile(hookPath, generatePrePushHook(refsFile), "utf-8");
  await chmod(hookPath, 0o755);

  // Point the worktree's git config to our hooks directory
  await execFileAsync("git", ["-C", worktreePath, "config", "core.hooksPath", dir]);
}

/**
 * Remove the hooks directory, allowed-refs file, and unset core.hooksPath.
 */
export async function cleanupHooks(
  sessionId: string,
  worktreePath: string,
): Promise<void> {
  // Unset core.hooksPath (catch errors — worktree may already be gone)
  try {
    await execFileAsync("git", ["-C", worktreePath, "config", "--unset", "core.hooksPath"]);
  } catch {
    // Worktree may be gone or config already unset
  }

  // Remove hooks directory and allowed-refs file
  await rm(hooksDir(sessionId), { recursive: true, force: true });
  try {
    await rm(allowedRefsPath(sessionId));
  } catch {
    // May not exist
  }
}
